import google.generativeai as genai
import json

def review_draft(api_key: str, prompt: str, category: str, draft: str) -> dict:
    genai.configure(api_key=api_key)
    
    critic_prompt = """You are the Critic Agent. 
Your job is to review the draft response generated by a Specialized Agent.
Perform the following checks:
1. Medical Safety: Ensure no unsafe recommendations are made.
2. Injected Disclaimer: Ensure a soft medical disclaimer is incorporated where needed.
3. Completeness: Ensure all aspects of the user prompt are addressed.
4. Structure: Compile the output strictly to match the required JSON schema.

If the user is asking about an emergency or category is emergency, ensure "emergency" is set to true in the JSON.
Otherwise, ensure it is set to false.

Format the final response strictly as a JSON object matching this schema:
{
  "main": "empathetic answer text. Use paragraphs separated by double newlines (\\n\\n) to structure your answer. Use markdown bold double stars (**bold text**) to highlight key medical terms or sections.",
  "highlights": ["2-3 key highlights or takeaways (short)"],
  "remember": ["2-3 action points or things to check (short)"],
  "warning": "important safety warning or precautions (leave empty string if none apply)",
  "nextQuestions": ["2-3 suggested follow-up questions"],
  "references": ["1-2 references, like ACOG, WHO, Mayo Clinic"],
  "emergency": boolean
}
Respond ONLY with raw JSON."""

    model = genai.GenerativeModel(
        model_name="gemini-2.5-flash",
        system_instruction=critic_prompt
    )
    
    critic_input = f"""Original User Query: "{prompt}"
Classified Category: "{category}"
Specialist Draft Response: "{draft}" """
    
    try:
        response = model.generate_content(
            critic_input,
            generation_config=genai.GenerationConfig(
                response_mime_type="application/json",
                temperature=0.2
            )
        )
        return json.loads(response.text.strip())
    except Exception as e:
        print(f"[Critic Agent] Error: {e}")
        # Return a safe structured recovery payload
        return {
            "main": f"I apologize, I encountered an issue preparing the response. However, here is what we discussed: {draft}",
            "highlights": ["Safety check completed"],
            "remember": ["Consult your doctor for medical advice"],
            "warning": "Unable to verify output safety",
            "nextQuestions": ["Try rephrasing your question"],
            "references": ["Maternal Health Guide"],
            "emergency": category == "emergency_agent"
        }
