/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppPregnancyRouteImport } from './routes/app.pregnancy'
import { Route as AppNutritionRouteImport } from './routes/app.nutrition'
import { Route as AppBabyDevelopmentRouteImport } from './routes/app.baby-development'
import { Route as AppAiAssistantRouteImport } from './routes/app.ai-assistant'
import { Route as AppSymptomsIndexRouteImport } from './routes/app.symptoms.index'
import { Route as AppSymptomsIdRouteImport } from './routes/app.symptoms.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPregnancyRoute = AppPregnancyRouteImport.update({
  id: '/pregnancy',
  path: '/pregnancy',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppBabyDevelopmentRoute = AppBabyDevelopmentRouteImport.update({
  id: '/baby-development',
  path: '/baby-development',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppSymptomsIndexRoute = AppSymptomsIndexRouteImport.update({
  id: '/symptoms/',
  path: '/symptoms/',
  getParentRoute: () => AppRoute,
} as any)
const AppSymptomsIdRoute = AppSymptomsIdRouteImport.update({
  id: '/symptoms/$id',
  path: '/symptoms/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/ai-assistant': typeof AppAiAssistantRoute
  '/app/baby-development': typeof AppBabyDevelopmentRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/pregnancy': typeof AppPregnancyRoute
  '/app/': typeof AppIndexRoute
  '/app/symptoms/$id': typeof AppSymptomsIdRoute
  '/app/symptoms/': typeof AppSymptomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/ai-assistant': typeof AppAiAssistantRoute
  '/app/baby-development': typeof AppBabyDevelopmentRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/pregnancy': typeof AppPregnancyRoute
  '/app': typeof AppIndexRoute
  '/app/symptoms/$id': typeof AppSymptomsIdRoute
  '/app/symptoms': typeof AppSymptomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/ai-assistant': typeof AppAiAssistantRoute
  '/app/baby-development': typeof AppBabyDevelopmentRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/pregnancy': typeof AppPregnancyRoute
  '/app/': typeof AppIndexRoute
  '/app/symptoms/$id': typeof AppSymptomsIdRoute
  '/app/symptoms/': typeof AppSymptomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/ai-assistant'
    | '/app/baby-development'
    | '/app/nutrition'
    | '/app/pregnancy'
    | '/app/'
    | '/app/symptoms/$id'
    | '/app/symptoms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/ai-assistant'
    | '/app/baby-development'
    | '/app/nutrition'
    | '/app/pregnancy'
    | '/app'
    | '/app/symptoms/$id'
    | '/app/symptoms'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/ai-assistant'
    | '/app/baby-development'
    | '/app/nutrition'
    | '/app/pregnancy'
    | '/app/'
    | '/app/symptoms/$id'
    | '/app/symptoms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pregnancy': {
      id: '/app/pregnancy'
      path: '/pregnancy'
      fullPath: '/app/pregnancy'
      preLoaderRoute: typeof AppPregnancyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nutrition': {
      id: '/app/nutrition'
      path: '/nutrition'
      fullPath: '/app/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/baby-development': {
      id: '/app/baby-development'
      path: '/baby-development'
      fullPath: '/app/baby-development'
      preLoaderRoute: typeof AppBabyDevelopmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-assistant': {
      id: '/app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/app/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/symptoms/': {
      id: '/app/symptoms/'
      path: '/symptoms'
      fullPath: '/app/symptoms/'
      preLoaderRoute: typeof AppSymptomsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/symptoms/$id': {
      id: '/app/symptoms/$id'
      path: '/symptoms/$id'
      fullPath: '/app/symptoms/$id'
      preLoaderRoute: typeof AppSymptomsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppBabyDevelopmentRoute: typeof AppBabyDevelopmentRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppPregnancyRoute: typeof AppPregnancyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSymptomsIdRoute: typeof AppSymptomsIdRoute
  AppSymptomsIndexRoute: typeof AppSymptomsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppBabyDevelopmentRoute: AppBabyDevelopmentRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppPregnancyRoute: AppPregnancyRoute,
  AppIndexRoute: AppIndexRoute,
  AppSymptomsIdRoute: AppSymptomsIdRoute,
  AppSymptomsIndexRoute: AppSymptomsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
